plugin:
  has_options: false
  icon: res_advert.png

  resources:
    - class: Claroline\AnnouncementBundle\Entity\AnnouncementAggregate
      name: claroline_announcement_aggregate

  widgets:
    - name: claroline_announcement_widget
      is_configurable: false
